#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setup Emacs daemon and ec alias to connect to it
alias ec='emacsclient -nw'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/fpoms/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/fpoms/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/fpoms/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/fpoms/google-cloud-sdk/completion.zsh.inc'; fi

# added by travis gem
[ -f /Users/fpoms/.travis/travis.sh ] && source /Users/fpoms/.travis/travis.sh

export PATH="/Users/fpoms/Library/Python/3.9/bin:$PATH"
eval "$(direnv hook zsh)"

source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
