#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH="$HOME/.npm-packages/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/Cellar/node/7.2.0/bin:$PATH"
export PYTHONPATH="/opt/opencv-3.1.0/lib/python2.7/site-packages:$PYTHONPATH"

# Setup Emacs daemon and ec alias to connect to it
alias ec='emacsclient -nw'
# Start Emacs daemon on first ec usage
export ALTERNATE_EDITOR=''
alias tmux="TERM=screen-256color-bce tmux"

# Keep ssh key accessed
eval `keychain --eval id_rsa`

